name: Run pre-commit checks

on: [pull_request]

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Set up Python 3.8
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit check for all files
        run: |
          pre-commit run --all-files
